-- local lazydev = require('lazydev')
--
-- local plugin_path = vim.g.sams_super_secret_plugin_path
--
-- lazydev.setup {
--   library = {
--     { path = vim.fn.expand('~/workspace/nvim_stuff/luvit-meta/library'), words = { 'vim%.uv' } },
--   },
-- }
